language: python

python:
  - "3.4"
  - "3.5"

install:
  - "pip install boto cryptography flake8 mock psycopg2 pylint pytest python-dateutil python-snappy python-systemd requests"

script:
  - "make pylint"
  - "make flake8"
  - "make unittest"

addons:
  apt:
    packages:
      - libsnappy-dev
      - postgresql-9.4
