language: python

python:
  - "3.5"
  - "3.6"

install:
  - "pip install boto cryptography flake8 httplib2 mock psycopg2 pylint pytest python-dateutil python-snappy python-systemd requests azure azure-storage"

script:
  - "make pylint"
  - "make flake8"
  - "make unittest"

addons:
  apt:
    packages:
      - libsnappy-dev
      - postgresql-9.4
